server:  port: 8080
spring:  mail:    host: smtp.gmail.com
    port: 587
    username: user@gmail.com
    password: password
    properties:      mail:
        smtp:
          auth: true
          starttls:
            enable: true  rabbitmq:    host: rabbitmq    port: 5672    username: user    password: pass